export const SET_SCREEN_DATA = 'SET_SCREEN_DATA'

export const SET_B_MAP = 'SET_B_MAP'

export const SET_ESTATE_EDIT = 'SET_ESTATE_EDIT'

export const SET_ECHART_SCREEN_CLEAR = 'SET_ECHART_SCREEN_CLEAR'

export const SET_ECHART_SCREEN = 'SET_ECHART_SCREEN'

export const SET_ECHART_SCREEN_CHURRENT = 'SET_ECHART_SCREEN_CHURRENT'

export const SET_IS_SHOW_SCREEN = 'SET_IS_SHOW_SCREEN'

export const SET_LOADER_CENTER = 'SET_LOADER_CENTER'

export const SET_MAIL_REPLY = 'SET_MAIL_REPLY'

export const SET_MAIL_LIKESTR = 'SET_MAIL_LIKESTR'

export const SET_CONTRACT_ONE_DATA = 'SET_CONTRACT_ONE_DATA'


